production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: ip
  database: j
  username: c
  password: u

development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: ip
  database: j
  username: c
  password: u

