source "http://ruby.taobao.org"

gem "sinatra"
gem "grape"
gem "grape-entity"
gem "activerecord", "~> 4.0.0"
gem "mysql2"
gem "rake"
gem "thin"

group :development, :test do
  gem "rspec"
  gem "database_cleaner"
  gem "rack-test", require: "rack/test"
  gem "awesome_print"
  gem "shotgun"
end
