production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: ip
  database: jc
  username: c
  password: H

development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: ip
  database: j
  username: c
  password: HT

